### ISSUE TITLE
example python

### ISSUE THREAD

**Issue by simonmarti1992** [pollination/utci-comfort-map#175]
Is there a way to create an utci map from pure-python code ? 
let's imagine having the building geometry from`.geojson` file and weather data from `.epw` ? 
Best regards

**Comment by mostaphaRoudsari** [comment]
Hi, @simonmarti1992 - The short answer is yes but you need to generate the sensor grids at some point during the process. Let's continue the conversation on [Pollination Discourse](https://discourse.pollination.cloud/c/recipes/9). This can be a useful question for others too.
